### ISSUE TITLE
Also add index on comid

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-crawler#219]
With the larger tables from wade and the census blocks, it's becoming clear that we need indexes on the feature tables. 

The crawler should be adding a comid index to help improve join performance. 

https://github.com/internetofwater/nldi-crawler/blob/master/src/main/resources/mybatis/mappers/ingest.xml#LL30C4-L30C4 seems to be where it is being handled during ingest. 

It looks like it maybe adopts from this? https://github.com/internetofwater/nldi-db/blob/d372160066d343ddd671124049a6e2e95488c1b2/liquibase/changeLogs/nldi/nldi_data/indexes/featureId.yml#L4 ?

Maybe @EthanGrahn can pop in and give us a pointer on a quick way to add a comid index?

**Comment by EthanGrahn** [comment]
I'd be happy to! I'll dig into this a little tomorrow to see what I can find.

**Comment by dblodgett-usgs** [comment]
Awesome. Thanks!! 

The crawler is adding indexes for the tables that get added like:

![image](https://github.com/internetofwater/nldi-crawler/assets/1492803/09533cf6-2362-488e-9c49-98b194a12baa)

Based on what appears to be a template table. 

![image](https://github.com/internetofwater/nldi-crawler/assets/1492803/0cd7c603-e29d-40f0-b815-a7f13282e780)

My testing on dev leads me to believe that adding an index on the comid column will get these very large tables to function rather than timing out.

**Comment by EthanGrahn** [comment]
I was just typing out my response as you made that commit. I'll take a look.

**Comment by dblodgett-usgs** [comment]
I just ripped off the existing "identifier" index and find/replaced `identifier` to `comid`.

**Comment by EthanGrahn** [comment]
I'd recommend changing [this line](https://github.com/dblodgett-usgs/nldi-db/commit/61cecf30d61fe9a8d587220ae123289cbef8ba85#diff-832eae6f1a03f83b2862392bb6670b39d4cbd6b0c32f19ac91e0195775371821R16) to `create.index.nldi_data.feature_comid_idx` just in case liquibase skips that because the id has been run in the past. Not sure why I used that ambiguous id.

**Comment by dblodgett-usgs** [comment]
That block appears to work against all the feature tables where the one above it does the primary/template one?

I just switched it to:
`id: "create.index.nldi_data.all_feature_comid_idx"` and `id: "create.index.nldi_data.all_feature_identifier_idx"` Seem ok?

**Comment by EthanGrahn** [comment]
That's right. The first one will update the base table that all future tables will copy from and automatically inherit the index. The second one makes sure all current tables get that index. Those IDs look good. The identifier index will likely run again, but it has preconditions to check whether the index already exists, so nothing should change.

**Comment by dblodgett-usgs** [comment]
Fixed in https://github.com/internetofwater/nldi-db/pull/104 Thanks for the boost @EthanGrahn
