### ISSUE TITLE
Add WaDE sites to NLDI

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-crawler#75]
A NLDI-ready geojson of sites from the WaDE 2.0 services is available here: https://www.hydroshare.org/resource/5f665b7b82d74476930712f7e423a0d2/

source_name: `Water Data Exchange 2.0 Sites`
source_suffix: `wade`
source_uri: `https://www.hydroshare.org/resource/5f665b7b82d74476930712f7e423a0d2/data/contents/wade.geojson`
feature_id: `feature_id`
feature_name: `feature_name`
feature_uri: `feature_uri`
feature_reach: `NULL`
feature_measure: `NULL`
ingest_type: `point`

If the team is not comfortable adding this to production, it would be ok in the near term to have it on beta/QA. It includes about 1M points.

<img width="1040" alt="Screen Shot 2020-05-16 at 8 19 26 AM" src="https://user-images.githubusercontent.com/1492803/82120757-fe1fe300-974d-11ea-8e10-e4e0b46c0a60.png">

**Comment by jkreft-usgs** [comment]
Fancy!  I am working on getting this in now

**Comment by jkreft-usgs** [comment]
WaDE metadata has been added to the database.  The first crawl failed due to a network issue (It looks like it was only able to download about 2/3 of the file) but the second download was successful and it is indexing now

**Comment by dblodgett-usgs** [comment]
Done and dusted. Thanks @jkreft-usgs !!
